### ISSUE TITLE
Is there any other way to download checkpoint?

### ISSUE THREAD

**Issue by ginlock** [yuweihao/KERN#10]
I can't open google drive,is there any other path to down load checkpoint such as baidu desk. I am eager for your reply.Thank you a lot.

**Comment by yuweihao** [comment]
Hi @ginlock , we don't upload the checkpoints to Baidu Cloud Drive. Recently I have graduated from my university and the network where I am staying now is not good. It may be time-consuming and difficult for me to upload the checkpoints to Baidu Cloud Drive. Once I succeed, I will send the Baidu Drive links to you.

**Comment by ZhecanJamesWang** [comment]
Please share the checkpoint on google drive or any other platform at least. That would also be very helpful. Thanks a lot!

**Comment by yuweihao** [comment]
Hi @ZhecanJamesWang , we had shown the Google Drive link in the README before. https://drive.google.com/open?id=1yCQfZRCt6UF-C-jSq78NaF9IUyNplLFx
