### ISSUE TITLE
Inference on custom image outside visual genome dataset

### ISSUE THREAD

**Issue by mrfarazi** [yuweihao/KERN#11]
I was wondering if you support inference on custom image. For example, if I wanted to generate scene-graph using your pre-trained models from a custom image not in visual genome dataset, would I be able to do that.

**Comment by yuweihao** [comment]
Hi @mrfarazi , this repo is based on the repo [neural-motifs](https://github.com/rowanz/neural-motifs/) and you could refer to this issue https://github.com/rowanz/neural-motifs/issues/26

**Comment by mrfarazi** [comment]
Thanks!
