### ISSUE TITLE
Predicted relations on evaluation images 

### ISSUE THREAD

**Issue by astrosaeed** [yuweihao/KERN#12]
Hello,
I am trying to print out the predicted relations on evaluation images here:
https://github.com/yuweihao/KERN/blob/master/models/eval_rels.py#L70

To my surprise, the relations (rels_i) are tuples of size 2 (only including objects not relations) while gt_relations are size 3 (as expected). Can you help me on that?

**Comment by yuweihao** [comment]
Hi @astrosaeed , the relations are in this line represented by the scores of relations https://github.com/yuweihao/KERN/blob/master/models/eval_rels.py#L72.

**Comment by astrosaeed** [comment]
Thanks. 
I was incorrectly looking at the wrong variable. I have one more question about the prediction scores:
The total number of predicates are 50 (in VG-SGG-dict.json) but the prediction score has 51 columns with the first column always having the maximum value. What is the extra column for?

**Comment by yuweihao** [comment]
Hi @astrosaeed , it means ```no relationship```.
