### ISSUE TITLE
cudaCheckError() failed : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by ankitsamal** [yuweihao/KERN#14]
I am getting the following error trace when I execute `CUDA_VISIBLE_DEVICES=0 ./scripts/eval_kern_predcls.sh`

> `save_rel_recall : results/kern_rel_recall_predcls.pkl
Unexpected key ggnn_obj_reason.obj_proj.weight in state_dict with size torch.Size([512, 4096])
Unexpected key ggnn_obj_reason.obj_proj.bias in state_dict with size torch.Size([512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq3_w.weight in state_dict with size torch.Size([512, 1024])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq3_w.bias in state_dict with size torch.Size([512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq3_u.weight in state_dict with size torch.Size([512, 512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq3_u.bias in state_dict with size torch.Size([512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq4_w.weight in state_dict with size torch.Size([512, 1024])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq4_w.bias in state_dict with size torch.Size([512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq4_u.weight in state_dict with size torch.Size([512, 512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq4_u.bias in state_dict with size torch.Size([512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq5_w.weight in state_dict with size torch.Size([512, 1024])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq5_w.bias in state_dict with size torch.Size([512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq5_u.weight in state_dict with size torch.Size([512, 512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_eq5_u.bias in state_dict with size torch.Size([512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_output.weight in state_dict with size torch.Size([512, 1024])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_output.bias in state_dict with size torch.Size([512])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_obj_cls.weight in state_dict with size torch.Size([151, 77312])
Unexpected key ggnn_obj_reason.ggnn_obj.fc_obj_cls.bias in state_dict with size torch.Size([151])
  0%|                                                                                                                                                                     | 0/26446 [00:00<?, ?it/s]cudaCheckError() failed : no kernel image is available for execution on the device`

**Comment by kunalpagarey** [comment]
@ankitsamal I am facing the same error. Please let me know the solution if you have solved it.

Thanks.

**Comment by yuweihao** [comment]
The repo is based on [neural-motifs](https://github.com/rowanz/neural-motifs). Maybe can try the method in this issue https://github.com/rowanz/neural-motifs/issues/14

**Comment by kunalpagarey** [comment]
@yuweihao Thanks for your quick reply. I tried to solve it as discussed in issue [rowanz/neural-motifs#14](https://github.com/rowanz/neural-motifs/issues/14) but I am still getting the same error. What else could be the reason for this error? Is there any other solution?

Can the evaluation be performed using CPU & RAM only, if yes, please guide me through the changes?

**Comment by yuweihao** [comment]
Hi @kunalpagarey , I don't have idea right now. Maybe update your CUDA path in Makefile file and run `make` in the main directory again.

**Comment by kunalpagarey** [comment]
Actually the solution here [rowanz/neural-motifs#14](https://github.com/rowanz/neural-motifs/issues/14) works. The reason it was not working for me is because I was not deleting the old compiled files before running the changed Makefiles.
Now it works fine for me and Thank you @yuweihao for your nice work.

**Comment by yuweihao** [comment]
@kunalpagarey (^_^)
