### ISSUE TITLE
Understanding the equations in the paper.

### ISSUE THREAD

**Issue by kunalpagarey** [yuweihao/KERN#16]
@yuweihao I was reading your paper (KERN) and wanted to make sure that there is no mistake in equation 6. You explain it as: all correlated output feature vectors are aggregated to predict the class label but you have also used the hidden state of the last class i.e. h_iC, I am confused. Could you please clarify it.

Thanks.

**Comment by yuweihao** [comment]
For i-th object region, we use C nodes in the graph to represent the region, namely, h_i1, h_i2, h_i3, ..., h_iC. If we have O object region in the image, the graph for object classification will have C*O nodes. After graph propagation, for each region, we concat all output features of the C nodes of the region for object classification.

**Comment by kunalpagarey** [comment]
So in this equation ![e5](https://user-images.githubusercontent.com/38290549/75946995-c4686b80-5ec4-11ea-8769-1589da21fbf3.png) there should not be **h_iC** in the end instead it should be **f_iC**, right?

**Comment by yuweihao** [comment]
Yes, you are right. This is a typo. It should be $f_iC$.
