### ISSUE TITLE
facing an issue in training 

### ISSUE THREAD

**Issue by DeepaliVerma** [yuweihao/KERN#17]
ImportError: /home/KERN/lib/fpn/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration

please give suggestion how to resolve this issue.

**Comment by yuweihao** [comment]
Hi @DeepaliVerma , maybe you can refer to this issue https://github.com/rusty1s/pytorch_scatter/issues/19  . Make sure the CUDA version in your system is also 9.0, the same as that of PyTorch.
