### ISSUE TITLE
cannot import name 'calculate_mR_from_evaluator_list'

### ISSUE THREAD

**Issue by taoqi95** [yuweihao/KERN#22]
Hello, I encountered the following problem in the process of reproducing the code. How can you solve this problem? Thank you.
Traceback (most recent call last):
  File "models/train_rels.py", line 17, in <module>
    from lib.evaluation.sg_eval import BasicSceneGraphEvaluator, calculate_mR_from_evaluator_list, eval_entry
ImportError: cannot import name 'calculate_mR_from_evaluator_list'

**Comment by yuweihao** [comment]
Hi @taoqi95 please make sure that you use the updated code by `git clone https://github.com/yuweihao/KERN.git`.

**Comment by taoqi95** [comment]
Thank you.There no errors in your code.My Ubuntu system can not find code current path.&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Weihao Yu"<notifications@github.com&gt;; 
发送时间: 2021年2月15日(星期一) 下午5:01
收件人: "yuweihao/KERN"<KERN@noreply.github.com&gt;; 
抄送: "410324026"<410324026@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yuweihao/KERN] cannot import name &#39;calculate_mR_from_evaluator_list&#39; (#22)





 
Hi @taoqi95 please make sure that you use the updated code by git clone https://github.com/yuweihao/KERN.git.
