### ISSUE TITLE
An error while running the code

### ISSUE THREAD

**Issue by DanZhang123** [yuweihao/KERN#3]
While training _the pretrain VG detection_ with the **./scripts/pretrain-detector.sh** command, there was an error: No module named 'dataloaders.mscoco' . what should I do?

**Comment by yuweihao** [comment]
Hi @DanZhang123 ,

Thanks for reporting this error. Just remove the line ```from dataloaders.mscoco import CocoDetection, CocoDataLoader``` in ```train_detector.py```. I also update this file by removing this line and some code related to ```conf.coco```. Because according to the experience of @rowanz in his repo [neural-motifs](https://github.com/rowanz/neural-motifs), it is not necessary to train COCO, and training VG is enough.

**Comment by DanZhang123** [comment]
Thank you @yuweihao

**Comment by DanZhang123** [comment]
Hi @yuweihao 
 The package I downloaded from 

> https://drive.google.com/open?id=11zKRr2OF5oclFL47kjFYBOxScotQzArX

 under this link cannot be decompressed. so I want to confirm whether the package you uploaded is correct.

**Comment by yuweihao** [comment]
@DanZhang123 Hi, the file is a checkpoint and it doesn't need to be decompressed. Just download it. (^_^)

**Comment by DanZhang123** [comment]
你好，但是下载下来的文件的后缀是.tar的，不是pth的，但tar文件无法解压。


| |
张丹
邮箱：danzhang163com@163.com
|

签名由 网易邮箱大师 定制

On 04/04/2019 22:22, Weihao Yu wrote:

@DanZhang123 Hi, the file is a checkpoint and it doesn't need to be decompressed. Just download it. (^_^)

**Comment by yuweihao** [comment]
> 你好，但是下载下来的文件的后缀是.tar的，不是pth的，但tar文件无法解压。 | | 张丹 邮箱：danzhang163com@163.com | 签名由 网易邮箱大师 定制 On 04/04/2019 22:22, Weihao Yu wrote: @DanZhang123 Hi, the file is a checkpoint and it doesn't need to be decompressed. Just download it. (^_^) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Hi, @DanZhang123 , habitually, the suffix of checkpoints could be named "tar" or "pth", and the suffix is not important. 

你好呀张丹，tar和pth都有人用来当作checkpoint的后缀名，下载下来直接加载模型就好，无需解压。

Weihao

**Comment by DanZhang123** [comment]
好的，谢谢你^•^




| |
张丹
邮箱：danzhang163com@163.com
|

签名由 网易邮箱大师 定制

On 04/04/2019 22:45, Weihao Yu wrote:

你好，但是下载下来的文件的后缀是.tar的，不是pth的，但tar文件无法解压。 | | 张丹 邮箱：danzhang163com@163.com | 签名由 网易邮箱大师 定制 On 04/04/2019 22:22, Weihao Yu wrote: @DanZhang123 Hi, the file is a checkpoint and it doesn't need to be decompressed. Just download it. (^_^) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Hi, @DanZhang123 , habitually, the suffix of checkpoints could be named "tar" or "pth", and the suffix is not important.

你好呀张丹，tar和pth都有人用来当作checkpoint的后缀名，下载下来直接加载模型就好，无需解压。

Weihao

**Comment by yuweihao** [comment]
> 好的，谢谢你^•^ | | 张丹 邮箱：danzhang163com@163.com | 签名由 网易邮箱大师 定制 On 04/04/2019 22:45, Weihao Yu wrote: 你好，但是下载下来的文件的后缀是.tar的，不是pth的，但tar文件无法解压。 | | 张丹 邮箱：danzhang163com@163.com | 签名由 网易邮箱大师 定制 On 04/04/2019 22:22, Weihao Yu wrote: @DanZhang123 Hi, the file is a checkpoint and it doesn't need to be decompressed. Just download it. (^_^) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. Hi, @DanZhang123 , habitually, the suffix of checkpoints could be named "tar" or "pth", and the suffix is not important. 你好呀张丹，tar和pth都有人用来当作checkpoint的后缀名，下载下来直接加载模型就好，无需解压。 Weihao — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

不客气 : )
