### ISSUE TITLE
About the training phases

### ISSUE THREAD

**Issue by kellyiss** [yuweihao/KERN#4]
In Step 5
Train scene graph classification: run CUDA_VISIBLE_DEVICES=YOUR_GPU_NUM ./scripts/train_kern_predcls.sh.  

a mistake? run ./scripts/train_kern_sgcls.sh ?

**Comment by wh-yu** [comment]
Hi @kellyiss , thanks for your reminder. It is a typo and as you guess, it should be ```run ./scripts/train_kern_sgcls.sh```

**Comment by yuweihao** [comment]
Hi @kellyiss , thanks for your reminder. It is a typo and I have fixed it. As you guess, it should be ```run ./scripts/train_kern_sgcls.sh```.
