### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by MitraTj** [yuweihao/KERN#6]
Hi there,

Is there any code to visualize detection and your model result?

Thanks!

**Comment by yuweihao** [comment]
Hi @MitraTj , thanks for noticing our work.

I have wrote code to show qualitative results of sgcls task and I could release or share it with you. Give me a few days to arrange the code to make it easy to read and use.

**Comment by wh-yu** [comment]
@MitraTj , I have released visualization code for sgcls task. Please refer to ```visualization/visulize_sgcls.pkl``` in the repo.

**Comment by yuweihao** [comment]
@MitraTj , I have released visualization code for sgcls task. Please refer to ```visualization/visulize_sgcls.pkl``` in the repo.

**Comment by MitraTj** [comment]
Thanks @yuweihao I appreciate your efforts.

**Comment by MitraTj** [comment]
Another question is where did you make KERN_sgcls.pkl?

**Comment by yuweihao** [comment]
run ```CUDA_VISIBLE_DEVICES=YOUR_GPU_NUM ./scripts/eval_kern_sgcls.sh```, refering to step 6 in README.

**Comment by yuweihao** [comment]
or you could download it from this folder [Google Drive](https://drive.google.com/open?id=1yCQfZRCt6UF-C-jSq78NaF9IUyNplLFx).
