### ISSUE TITLE
Question about generate_knowledge.py

### ISSUE THREAD

**Issue by ystluffy** [yuweihao/KERN#9]
Hi,
line 32 of generate_knowledge.py `mat[gt_classes[i], gt_classes[j]] += 1`
Should it be `mat[gt_classes_list[i], gt_classes_list[j]] += 1` because there are repeated labels in gt_classes

**Comment by yuweihao** [comment]
Hi @ystluffy , I check the code and as you say, it should be ```mat[gt_classes_list[i], gt_classes_list[j]] += 1```.  With this new line of code, I think the generated object cooccurrence matrix will be more accurate. Thank you a lot. I will comment this line of code and thank you in that.
